Feature/animation
infoshareacademy/jfdzl1-green-hornets pull request #14
Opened 2017-09-24 10:58 UTC by RadoslawStepniewski

Added animation to images

2017-09-25 07:00 UTC, patrykomiotek requested changes
Keep classes and CSS selectors in English

2017-09-25 07:00 UTC, patrykomiotek commented on css/style.css
> +.fotka:hover{
Why are you writing CSS selectors in Polish?

2017-09-25 07:00 UTC, patrykomiotek commented on css/style.css
> +
Same as above

2017-09-25 07:00 UTC, patrykomiotek commented on index.html
> +    $(document).ready(function () {
Have you tried without jQuery first? ;)

2017-10-01 10:06 UTC, burunia approved these changes

2017-10-01 10:06 UTC, burunia commented on index.html
> +
remove white space

2017-10-01 10:10 UTC, merged